/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnitest_Registry */


// Data structures
struct position {
  float x;
  float y;
};

struct velocity {
  float dx;
  float dy;
};


#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL printAllEntities();

JNIEXPORT void JNICALL init(void);

JNIEXPORT position* JNICALL getPositions(void);

JNIEXPORT int JNICALL getCapacity(void);

JNIEXPORT void JNICALL registerPosition(position&);

JNIEXPORT void JNICALL registerPositions(position pos[], int length);

JNIEXPORT int JNICALL update();

#ifdef __cplusplus
}
#endif
